---
- name: Deploy Tomcat Docker container
  hosts: all
  become: true

  vars:
    # These are DEFAULTS. They will be overwritten by Jenkins.
    container_name: "tomcat_prod" 
    app_port: "8082"
    docker_image: "spytroxx/my-tomcat-new" 
    docker_tag: "latest"

  tasks:
    - name: Install Docker (Amazon Linux)
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull application image from DockerHub
      docker_image:
        name: "{{ docker_image }}" # Variable
        tag: "{{ docker_tag }}"    # Variable
        source: pull

    - name: Stop old container if exists
      docker_container:
        name: "{{ container_name }}" # Variable
        state: absent
        force_kill: true

    - name: Run Tomcat container
      docker_container:
        name: "{{ container_name }}" # Variable
        image: "{{ docker_image }}:{{ docker_tag }}" # Combines variables
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:8080"
