---
- name: Deploy Tomcat Docker container
  hosts: all
  become: true

  vars:
    container_name: "tomcat_new"
    app_port: "8082"
    docker_image: "spytroxx/my-tomcat-new"
    docker_tag: "v2"

  tasks:

    - name: Install Docker (Amazon Linux)
      yum:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull application image from DockerHub (public)
      docker_image:
        name: "spytroxx/my-tomcat-new"
        tag: "v2"
        source: pull

    - name: Stop old container if exists
      docker_container:
        name: "tomcat-new"
        state: absent
        force_kill: true

    - name: Run Tomcat container
      docker_container:
        name: "tomcat-new"
        image: "spytroxx/my-tomcat-new:v2"
        state: started
        restart_policy: always
        ports:
          - "8082:8080"
